/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check. No auth. */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/server": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server info, available CLIs and the file token */
        get: operations["getServerInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server settings */
        get: operations["getSettings"];
        /** Change server settings, such as which CLI runs jobs */
        put: operations["putSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Home data, the topic list with the Continue item and the inbox count */
        get: operations["listTopics"];
        put?: never;
        /**
         * Create a topic from a link, an uploaded PDF or a name
         * @description JSON for a link or a name; multipart for a PDF. When `enrich` is true the server queues an enrich job and
         *     returns it.
         */
        post: operations["createTopic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics/{topic_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        /** One topic with its manifest, progress and jobs */
        get: operations["getTopic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename, archive or unarchive, or reorder resources */
        patch: operations["updateTopic"];
        trace?: never;
    };
    "/topics/{topic_id}/resources": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a file (audio, video, document) into the topic's outputs */
        post: operations["uploadResource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics/{topic_id}/resources/{resource_id}/rendered": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: components["parameters"]["TopicId"];
                resource_id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        /**
         * Make sure a pack or condensed doc has fresh HTML, and return where it is
         * @description Renders the Markdown when the HTML is missing, older than the Markdown, or from an older renderer.
         */
        get: operations["getRendered"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics/{topic_id}/mark-read": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark the topic as read. Adds its gap concepts to the profile with `via read`. */
        post: operations["markTopicRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Serve a library file. Supports Range requests so media can stream and seek. */
        get: operations["getFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/f/{file_token}/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Same as `/files/{path}`, authorised by the file token in the path
         * @description For `<audio>`, `<video>`, `<img>` and the Reader iframe. Because the token is part of the path, relative links
         *     inside rendered HTML (images, shared assets) resolve under it and keep working.
         */
        get: operations["getFileWithToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics/{topic_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        /** Playback and reading progress for a topic */
        get: operations["getProgress"];
        /** Save positions and done marks. Per item, the most recent `updated` wins. */
        put: operations["putProgress"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics/{topic_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start an enrich, deep enrich or condense job */
        post: operations["createJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List jobs. The app calls `?active=true` on every resume. */
        get: operations["listJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        /** Job state and its recent log lines */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer a job's questions. The server resumes the CLI session with them. */
        post: operations["answerJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a queued, running or waiting job */
        post: operations["cancelJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics/{topic_id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        /** The topic's conversation */
        get: operations["getChat"];
        put?: never;
        /**
         * Send a message
         * @description Saves the question, creates an empty assistant message and queues an `answer` job in the chat lane. The reply
         *     streams as `chat.delta` events and is saved as it grows, so a client that reconnects mid-reply sees all of
         *     it. Refused with 409 while the topic is enriching or condensing, because the job holds the topic's session.
         */
        post: operations["sendChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Files in `library/inbox/` that belong to no topic */
        get: operations["listInbox"];
        put?: never;
        /** Upload a file into the inbox */
        post: operations["uploadInbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inbox/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move an inbox file into an existing topic, or start a new topic from it */
        post: operations["assignInbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The person profile (`library/profile.md`) */
        get: operations["getProfile"];
        /** Replace the person profile */
        put: operations["putProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live event stream (Server-Sent Events)
         * @description `text/event-stream`. Each message has `id:` (an increasing integer), `event:` (the type) and `data:` (JSON,
         *     see `Event`). A comment line (`: ping`) is sent every 20 seconds. To replay what was missed, pass the last id
         *     as `Last-Event-ID` or `?after=`. If the id is older than the retained log, the server sends `resync` first
         *     and the client must refetch its snapshots.
         */
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** VAPID public key for Web Push */
        get: operations["getPushKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/subscriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a Web Push subscription */
        post: operations["addPushSubscription"];
        /** Remove a Web Push subscription */
        delete: operations["removePushSubscription"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                code: string;
                /** @description One plain sentence the app can show */
                message: string;
            };
        };
        Health: {
            ok: boolean;
            /** @constant */
            name: "studyo";
            version: string;
        };
        /** @enum {string} */
        CliId: "claude" | "opencode";
        CliInfo: {
            id: components["schemas"]["CliId"];
            label: string;
            installed: boolean;
            version?: string | null;
        };
        ServerInfo: {
            version: string;
            file_token: string;
            clis: components["schemas"]["CliInfo"][];
            settings: components["schemas"]["Settings"];
            storage: {
                library_bytes: number;
            };
        };
        Settings: {
            cli: components["schemas"]["CliId"];
            /** @description Optional model per CLI. Empty means the CLI's default. */
            models?: {
                claude?: string | null;
                /** @description provider/model */
                opencode?: string | null;
            };
        };
        /** @enum {string} */
        TopicStatus: "captured" | "enriching" | "ready" | "failed" | "archived";
        Origin: {
            /** @enum {string} */
            type: "link" | "pdf" | "topic";
            /** @description When type is link */
            link?: string;
            /** @description When type is topic */
            name?: string;
            /** @description When type is pdf, the path inside the topic folder */
            file?: string;
        };
        /** @enum {string} */
        ResourceType: "source" | "pack" | "condensed" | "audio" | "video";
        Resource: {
            id: string;
            type: components["schemas"]["ResourceType"];
            title: string;
            /** @description Relative to the topic folder */
            path: string;
            made_with?: string | null;
            /** @description Seconds, for audio and video */
            duration?: number | null;
            /** @description Bytes */
            size?: number | null;
            /** @description ISO date or date-time */
            added?: string;
            /** @description Derived by the server. Path of the rendered HTML next to a pack or condensed `.md`, when it exists. */
            html_path?: string | null;
            /** @description Derived by the server. For a source saved from the web, its original URL (from the ledger). */
            url?: string | null;
        };
        Learning: {
            goal?: string;
            gaps?: string[];
            updated?: string;
        };
        /** @description The topic manifest (`topic.json`) as the server sees it, after auto-discovery. */
        Topic: {
            id: string;
            title: string;
            status: components["schemas"]["TopicStatus"];
            origin: components["schemas"]["Origin"];
            /** @description The CLI session used for enrichment and chat */
            session_id?: string | null;
            /** @description Which CLI the session belongs to */
            session_cli?: components["schemas"]["CliId"] | null;
            resources: components["schemas"]["Resource"][];
            learning?: components["schemas"]["Learning"] | null;
            failure_reason?: string | null;
            created: string;
            updated: string;
        };
        TopicSummary: {
            id: string;
            title: string;
            status: components["schemas"]["TopicStatus"];
            origin: components["schemas"]["Origin"];
            counts: {
                sources: number;
                /** @description Pack plus condensed docs */
                docs: number;
                media: number;
            };
            progress: {
                /** @description Docs and media marked done */
                done: number;
                total: number;
            };
            failure_reason?: string | null;
            active_job?: components["schemas"]["Job"] | null;
            updated: string;
        };
        ContinueItem: {
            topic_id: string;
            topic_title: string;
            resource: components["schemas"]["Resource"];
            item: components["schemas"]["ProgressItem"];
        };
        TopicList: {
            topics: components["schemas"]["TopicSummary"][];
            continue: components["schemas"]["ContinueItem"] | null;
            inbox_count: number;
        };
        TopicDetail: {
            topic: components["schemas"]["Topic"];
            progress: components["schemas"]["Progress"];
            /** @description Active jobs first, then the most recent finished ones */
            jobs: components["schemas"]["Job"][];
        };
        TopicWithJob: {
            topic: components["schemas"]["Topic"];
            job: components["schemas"]["Job"] | null;
        };
        CreateTopic: {
            origin: {
                /** @enum {string} */
                type: "link" | "topic";
                /** Format: uri */
                link?: string;
                name?: string;
            };
            title?: string;
            /** @default true */
            enrich: boolean;
        };
        UpdateTopic: {
            title?: string;
            archived?: boolean;
            /** @description Resource ids in the new order. Ids not listed keep their relative order at the end. */
            resource_order?: string[];
        };
        Rendered: {
            /** @description Relative to the library root */
            html_path: string;
            renderer_version: string;
        };
        ProgressItem: {
            /** @description Seconds for audio and video; a 0–1 fraction of the page for documents */
            position: number;
            /** @description Seconds, for media */
            duration?: number | null;
            /** @description Heading id the reader was in, for documents */
            section?: string | null;
            done: boolean;
            /** Format: date-time */
            updated: string;
        };
        Progress: {
            items: {
                [key: string]: components["schemas"]["ProgressItem"];
            };
            /** @description The item most recently played or read in this topic */
            last: {
                resource_id: string;
                /** Format: date-time */
                updated: string;
            } | null;
        };
        ProgressUpdate: {
            resource_id: string;
            position: number;
            duration?: number | null;
            section?: string | null;
            done?: boolean;
            /**
             * Format: date-time
             * @description When the change happened on the device. An older update than the stored one is ignored.
             */
            updated: string;
        };
        /** @enum {string} */
        JobKind: "enrich" | "enrich-deep" | "condense" | "answer";
        /** @enum {string} */
        JobStatus: "queued" | "running" | "needs_input" | "succeeded" | "failed" | "cancelled";
        Job: {
            id: string;
            kind: components["schemas"]["JobKind"];
            topic_id: string;
            /**
             * @description Work jobs run one at a time; chat runs in its own lane so questions don't wait behind enrichment.
             * @enum {string}
             */
            lane: "work" | "chat";
            status: components["schemas"]["JobStatus"];
            cli: components["schemas"]["CliId"];
            /** @description Skill parameters, for example scope for condense */
            params?: {
                [key: string]: unknown;
            };
            /** @description The latest human-readable progress line */
            activity?: string | null;
            questions?: components["schemas"]["QuestionSet"] | null;
            error?: string | null;
            /** @description For answer jobs, a focus the reply offered to enrich */
            suggest_enrich?: string | null;
            /** Format: date-time */
            created: string;
            /** Format: date-time */
            started?: string | null;
            /** Format: date-time */
            finished?: string | null;
        };
        JobList: {
            jobs: components["schemas"]["Job"][];
        };
        LogLine: {
            seq: number;
            /** Format: date-time */
            at: string;
            /**
             * @description progress is a `[studyo]` line from a skill; tool is a tool call; text is model output
             * @enum {string}
             */
            kind: "progress" | "tool" | "text" | "stderr" | "system";
            text: string;
        };
        JobDetail: components["schemas"]["Job"] & {
            log: components["schemas"]["LogLine"][];
        };
        CreateJob: {
            /** @enum {string} */
            kind: "enrich" | "enrich-deep" | "condense";
            /** @description For condense, `all` or a list of pack section ids */
            scope?: "all" | string[];
            /** @description For enrich-deep, what to go deeper on */
            focus?: string;
        };
        /** @description Written by a skill when it needs the learner. The job waits in needs_input until answered. */
        QuestionSet: {
            id: string;
            title?: string;
            intro?: string;
            questions: components["schemas"]["Question"][];
            /** Format: date-time */
            asked: string;
        };
        Question: {
            id: string;
            /** @enum {string} */
            kind: "multi" | "single" | "text";
            label: string;
            help?: string;
            /** @default false */
            required: boolean;
            placeholder?: string;
            options?: {
                id: string;
                label: string;
                /** @description Heading to group options under */
                group?: string;
                /** @description Pre-selected */
                checked?: boolean;
                /** @description Why it is pre-selected, or what it builds on */
                note?: string;
            }[];
        };
        AnswerSet: {
            question_set_id: string;
            answers: {
                [key: string]: {
                    selected?: string[];
                    text?: string;
                };
            };
        };
        ChatMessage: {
            id: string;
            /** @enum {string} */
            role: "user" | "assistant";
            /** @description Markdown with reference-style citations */
            text: string;
            /** @enum {string} */
            status: "pending" | "streaming" | "complete" | "failed";
            job_id?: string | null;
            suggest_enrich?: string | null;
            error?: string | null;
            /** Format: date-time */
            created: string;
        };
        ChatHistory: {
            messages: components["schemas"]["ChatMessage"][];
            /** @description False while a work job holds the topic's session, or when there is no pack yet */
            available: boolean;
            unavailable_reason?: string | null;
        };
        SendChat: {
            text: string;
        };
        ChatTurn: {
            user: components["schemas"]["ChatMessage"];
            assistant: components["schemas"]["ChatMessage"];
            job: components["schemas"]["Job"];
        };
        InboxItem: {
            /** @description Relative to the library root */
            path: string;
            name: string;
            /** @enum {string} */
            kind: "pdf" | "audio" | "video" | "document" | "other";
            size: number;
            /** Format: date-time */
            added: string;
        };
        InboxList: {
            items: components["schemas"]["InboxItem"][];
        };
        AssignInbox: {
            path: string;
            /** @description Move into this topic */
            topic_id?: string;
            /** @description Or start a new topic from the file (PDFs become the topic's origin) */
            new_topic?: {
                title?: string;
                /** @default true */
                enrich: boolean;
            };
        };
        KnowsEntry: {
            term: string;
            /** @enum {string} */
            via: "self-reported" | "inferred" | "read" | "forgot";
            topic?: string;
            date?: string;
        };
        Profile: {
            knows: components["schemas"]["KnowsEntry"][];
            /** @description The free-text Markdown body */
            notes: string;
        };
        PushSubscription: {
            endpoint: string;
            keys: {
                p256dh: string;
                auth: string;
            };
        };
        /** @enum {string} */
        EventType: "resync" | "job.updated" | "job.log" | "chat.delta" | "chat.message" | "topic.updated" | "topic.removed" | "inbox.updated";
        /** @description The JSON in an SSE `data:` line. `id` repeats the SSE id. */
        Event: {
            id: number;
            type: components["schemas"]["EventType"];
            /** Format: date-time */
            at: string;
            data: components["schemas"]["JobUpdatedData"] | components["schemas"]["JobLogData"] | components["schemas"]["ChatDeltaData"] | components["schemas"]["ChatMessageData"] | components["schemas"]["TopicEventData"] | Record<string, never>;
        };
        JobUpdatedData: {
            job: components["schemas"]["Job"];
        };
        JobLogData: {
            job_id: string;
            line: components["schemas"]["LogLine"];
        };
        ChatDeltaData: {
            topic_id: string;
            message_id: string;
            /** @description Text to append */
            text: string;
        };
        ChatMessageData: {
            topic_id: string;
            message: components["schemas"]["ChatMessage"];
        };
        TopicEventData: {
            topic_id: string;
        };
    };
    responses: {
        /** @description Whole file */
        File: {
            headers: {
                "Accept-Ranges"?: "bytes";
                [name: string]: unknown;
            };
            content: {
                "application/octet-stream": string;
            };
        };
        /** @description Partial content */
        PartialFile: {
            headers: {
                "Content-Range"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/octet-stream": string;
            };
        };
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or wrong token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not allowed in the current state (for example a job already running on the topic) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        TopicId: string;
        ResourceId: string;
        JobId: string;
        /** @description Path relative to the library root, for example `topics/pc-ca-mcts/pack/pack.html`. May contain slashes. */
        FilePath: string;
        Range: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getServerInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerInfo"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    putSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Settings"];
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listTopics: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createTopic: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTopic"];
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    title?: string;
                    /** @default true */
                    enrich?: boolean;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicWithJob"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getTopic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateTopic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTopic"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Topic"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    uploadResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    title?: string;
                    /** @description For example NotebookLM */
                    made_with?: string;
                };
            };
        };
        responses: {
            /** @description Added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resource"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getRendered: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: components["parameters"]["TopicId"];
                resource_id: components["parameters"]["ResourceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rendered"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description The Markdown could not be rendered (unknown directive, missing asset) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    markTopicRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getFile: {
        parameters: {
            query?: never;
            header?: {
                Range?: components["parameters"]["Range"];
            };
            path: {
                /** @description Path relative to the library root, for example `topics/pc-ca-mcts/pack/pack.html`. May contain slashes. */
                path: components["parameters"]["FilePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["File"];
            206: components["responses"]["PartialFile"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Range not satisfiable */
            416: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getFileWithToken: {
        parameters: {
            query?: never;
            header?: {
                Range?: components["parameters"]["Range"];
            };
            path: {
                file_token: string;
                /** @description Path relative to the library root, for example `topics/pc-ca-mcts/pack/pack.html`. May contain slashes. */
                path: components["parameters"]["FilePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["File"];
            206: components["responses"]["PartialFile"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Range not satisfiable */
            416: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Progress"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    putProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgressUpdate"];
            };
        };
        responses: {
            /** @description The merged progress */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Progress"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJob"];
            };
        };
        responses: {
            /** @description Queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listJobs: {
        parameters: {
            query?: {
                /** @description Only queued, running and needs_input jobs */
                active?: boolean;
                topic_id?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getJob: {
        parameters: {
            query?: {
                log_lines?: number;
            };
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    answerJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerSet"];
            };
        };
        responses: {
            /** @description Accepted; the job is queued to resume */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    cancelJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getChat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatHistory"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    sendChat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topic_id: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendChat"];
            };
        };
        responses: {
            /** @description Queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatTurn"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listInbox: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    uploadInbox: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxItem"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    assignInbox: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignInbox"];
            };
        };
        responses: {
            /** @description Moved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicWithJob"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    putProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Profile"];
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    streamEvents: {
        parameters: {
            query?: {
                after?: number;
            };
            header?: {
                "Last-Event-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["Event"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getPushKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        public_key: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    addPushSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushSubscription"];
            };
        };
        responses: {
            /** @description Saved */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    removePushSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    endpoint: string;
                };
            };
        };
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
